# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-03-27 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerpathways', '0005_auto_20240316_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpathway',
            name='private_infill_completed',
            field=models.BooleanField(default=False, verbose_name=b'Private Infill Completed'),
        ),
    ]
