# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephantblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blogentries', to='elephantblog.Category', verbose_name='categories'),
        ),
    ]
