# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livinglots_organize', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('email_hash', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('facebook_page', models.CharField(blank=True, help_text=b'The Facebook page for your organization. Please do not enter your personal Facebook page.', max_length=256, null=True, verbose_name='facebook page')),
                ('post_publicly', models.BooleanField(default=True, help_text="Check this if you want to share your information on the lot's page so that your neighbors can reach you and work for access together. (If you don't click it, we'll just send you updates but keep your information hidden.)", verbose_name='post publicly')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livinglots_organize.OrganizerType')),
            ],
            options={
                'abstract': False,
                'permissions': (('email_organizers', 'Can send an email to all organizers'),),
            },
        ),
    ]
