# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0003_auto_20160720_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcher',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='watcher',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Watcher',
        ),
    ]
