# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organize', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('livinglots_lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livinglots_organize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StewardNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('email_hash', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('facebook_page', models.CharField(blank=True, help_text=b'The Facebook page for your organization. Please do not enter your personal Facebook page.', max_length=256, null=True, verbose_name='facebook page')),
                ('post_publicly', models.BooleanField(default=True, help_text="Check this if you want to share your information on the lot's page so that your neighbors can reach you and work for access together. (If you don't click it, we'll just send you updates but keep your information hidden.)", verbose_name='post publicly')),
                ('project_name', models.CharField(help_text='The name of the project using this lot.', max_length=256, verbose_name='project name')),
                ('support_organization', models.CharField(blank=True, help_text="What is your project's support organization, if any?", max_length=300, null=True, verbose_name='support organization')),
                ('land_tenure_status', models.CharField(choices=[(b'owned', 'project owns the land'), (b'licensed', 'project has a license for the land'), (b'lease', 'project has a lease for the land'), (b'access', 'project has access to the land'), (b'not sure', "I'm not sure")], default='not sure', help_text='What is the land tenure status for the project? (This will not be shared publicly.)', max_length=50, verbose_name='land tenure status')),
                ('include_on_map', models.BooleanField(default=True, help_text='Can we include the project on our map?', verbose_name='include on map')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livinglots_organize.OrganizerType')),
                ('use', models.ForeignKey(help_text='How is the project using the land?', on_delete=django.db.models.deletion.CASCADE, to='livinglots_lots.Use', verbose_name='use')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StewardProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='The name of the project using this lot.', max_length=256, verbose_name='project name')),
                ('support_organization', models.CharField(blank=True, help_text="What is your project's support organization, if any?", max_length=300, null=True, verbose_name='support organization')),
                ('land_tenure_status', models.CharField(choices=[(b'owned', 'project owns the land'), (b'licensed', 'project has a license for the land'), (b'lease', 'project has a lease for the land'), (b'access', 'project has access to the land'), (b'not sure', "I'm not sure")], default='not sure', help_text='What is the land tenure status for the project? (This will not be shared publicly.)', max_length=50, verbose_name='land tenure status')),
                ('include_on_map', models.BooleanField(default=True, help_text='Can we include the project on our map?', verbose_name='include on map')),
                ('started_here', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('external_id', models.CharField(blank=True, help_text='The external id for this project, if it is stored in other databases', max_length=100, null=True, verbose_name='external id')),
                ('date_started', models.DateField(blank=True, help_text='When did this project start?', null=True, verbose_name='date started')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('organizer', models.ForeignKey(blank=True, help_text='The organizer associated with this project.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Organizer', verbose_name='organizer')),
                ('steward_notification', models.ForeignKey(blank=True, help_text='The notification that led to the creation of this project, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='steward.StewardNotification', verbose_name='steward notification')),
                ('use', models.ForeignKey(help_text='How is the project using the land?', on_delete=django.db.models.deletion.CASCADE, to='livinglots_lots.Use', verbose_name='use')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
