# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_recentpostscontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArchiveContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogarchivecontent_set', to='page.Page')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
                'verbose_name_plural': 'blog archive',
                'db_table': 'page_page_blogarchivecontent',
                'verbose_name': 'blog archive',
                'permissions': [],
            },
        ),
    ]
