# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elephantblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('elephantblog.entry',),
        ),
    ]
