# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livinglots_owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('owner_type', models.CharField(choices=[(b'private', b'private'), (b'public', b'public'), (b'unknown', b'unknown')], default=b'private', max_length=20, verbose_name='owner type')),
                ('aliases', models.ManyToManyField(blank=True, help_text='Other names for this owner', to='livinglots_owners.Alias', verbose_name='aliases')),
            ],
            options={
                'ordering': ['owner_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OwnerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Owner')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OwnerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('owner_type', models.CharField(choices=[(b'private', b'private'), (b'public', b'public'), (b'unknown', b'unknown')], default=b'private', max_length=20, verbose_name='owner type')),
                ('owners', models.ManyToManyField(to='owners.Owner')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='default_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owners.OwnerContact'),
        ),
    ]
