# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('visible', models.BooleanField(default=True, help_text='Should lots with this use be visible on the map? If the use is not vacant and not a project that someone could join, probably not.', verbose_name='visible')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
