ALLOWED_ORIGIN = XXX
DB_NAME = XXX
DB_PASSWORD = XXX
DB_USER = XXX
PORT = XXX
PROJECT_NAME = XXX
REPO_NAME = XXX
TILESTACHE_ALLOWED_ORIGIN = XXX
TILESTACHE_PORT = XXX
TILESTACHE_WEBAPP_NAME = XXX
WEBAPP_NAME = xxx

centroid_view_sql = "CREATE OR REPLACE VIEW visible_centroids AS SELECT l.id AS id, l.commons_type, l.bbl, l.centroid, l.owner_id, l.priority, l.organizing, l.radpact_converted, l.radpact_planned, l.preservation_trust_voting_planned, l.preservation_trust_complete, l.private_infill_planned, l.section_8_pre_2014, l.demolition_proposed, l.demolition_completed, l.nycha_modernization_planned, l.nycha_modernization_complete, l.new_public_housing_built, l.new_public_housing_planned FROM lots_lot l WHERE l.group_id IS NULL AND l.centroid IS NOT NULL"
polygon_view_sql = "CREATE OR REPLACE VIEW visible_polygons AS SELECT l.id, l.commons_type, l.bbl, l.polygon, l.owner_id, l.priority, l.organizing, l.radpact_converted, l.radpact_planned, l.preservation_trust_voting_planned, l.preservation_trust_complete, l.private_infill_planned, l.section_8_pre_2014, l.demolition_proposed, l.demolition_completed, l.nycha_modernization_planned, l.nycha_modernization_complete, l.new_public_housing_built, l.new_public_housing_planned FROM lots_lot l WHERE l.group_id IS NULL AND l.polygon IS NOT NULL"

env:
	easy_install-2.7 pip
	pip2.7 install --user virtualenv
	pip2.7 install --user virtualenvwrapper

requirements:
	pip install -r ../requirements/base.txt
	pip install -r ../requirements/production.txt

install_node:
	bash install/node.sh

install_admin:
	mkdir -p $(HOME)/var
	-ln -s $(HOME)/webapps/$(WEBAPP_NAME)/deploy/admin $(HOME)/var/admin
	-ln -s $(HOME)/webapps/$(WEBAPP_NAME)/deploy/django $(HOME)/var/django
	cat templates/gunicorn.cfg | sed "s/<PORT>/$(PORT)/g; s/<WEBAPP_NAME>/$(WEBAPP_NAME)/g; s/<USER>/$(USER)/g;" > ../gunicorn.cfg
	cat templates/start_gunicorn.sh | sed "s/<PORT>/$(PORT)/g; s/<WEBAPP_NAME>/$(WEBAPP_NAME)/g; s/<PROJECT_NAME>/$(PROJECT_NAME)/g;" > ../start_gunicorn.sh

	mkdir -p $(HOME)/var/supervisor
	cat templates/supervisord.conf | sed "s/<PORT>/$(PORT)/g; s/<WEBAPP_NAME>/$(WEBAPP_NAME)/g; s/<USER>/$(USER)/g; s/<REPO_NAME>/$(REPO_NAME)/g; s/<PROJECT_NAME>/$(PROJECT_NAME)/g;" > $(HOME)/var/supervisor/supervisord.conf

	mkdir -p $(HOME)/var/tilestache
	cat templates/tilestache.cfg | sed "s/<ALLOWED_ORIGIN>/$(ALLOWED_ORIGIN)/g; s/<DB_NAME>/$(DB_NAME)/g; s/<DB_USER>/$(DB_USER)/g; s/<DB_PASSWORD>/$(DB_PASSWORD)/g;" > $(HOME)/var/tilestache/tilestache.cfg

install_tilestache:
	mkdir -p $(HOME)/webapps/$(TILESTACHE_WEBAPP_NAME)/logs
	cat templates/gunicorn.cfg | sed "s/<PORT>/$(TILESTACHE_PORT)/g; s/<WEBAPP_NAME>/$(TILESTACHE_WEBAPP_NAME)/g; s/<USER>/$(USER)/g;" > $(HOME)/webapps/$(TILESTACHE_WEBAPP_NAME)/gunicorn.cfg
	cat templates/tilestache_start_gunicorn.sh | sed "s/<PORT>/$(TILESTACHE_PORT)/g; s/<WEBAPP_NAME>/$(TILESTACHE_WEBAPP_NAME)/g; s/<VIRTUALENV>/$(WEBAPP_NAME)/g;" > $(HOME)/webapps/$(TILESTACHE_WEBAPP_NAME)/start_gunicorn.sh
	cat templates/tilestache.cfg | sed "s/<ALLOWED_ORIGIN>/$(TILESTACHE_ALLOWED_ORIGIN)/g; s/<DB_NAME>/$(DB_NAME)/g; s/<DB_USER>/$(DB_USER)/g; s/<DB_PASSWORD>/$(DB_PASSWORD)/g;" > $(HOME)/webapps/$(TILESTACHE_WEBAPP_NAME)/tilestache.cfg

install_tilestache_views:
	# Create convenience views for tilestache
	psql -U $(DB_USER) $(DB_NAME) -c $(centroid_view_sql)
	psql -U $(DB_USER) $(DB_NAME) -c $(polygon_view_sql)
