# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-13 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpathways', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewpathway',
            options={'verbose_name': '"Public Review Processes" pathway'},
        ),
    ]
