# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('livinglots_lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='centroid')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='polygon')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='name')),
                ('address_line1', models.CharField(blank=True, max_length=150, null=True, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=150, null=True, verbose_name='address line 2')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('state_province', models.CharField(blank=True, max_length=40, null=True, verbose_name='state/province')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='country')),
                ('known_use_certainty', models.PositiveIntegerField(default=0, help_text='On a scale of 0 to 10, how certain are we that the known use is correct?', verbose_name='known use certainty')),
                ('known_use_locked', models.BooleanField(default=False, help_text='Is the known use field locked? If it is not, the site will make a guess using available data. If you are certain that the known use is correct, lock it.', verbose_name='known use locked')),
                ('added', models.DateTimeField(auto_now_add=True, help_text=b'When this lot was added', verbose_name='date added')),
                ('added_reason', models.CharField(blank=True, help_text=b'The original reason this lot was added', max_length=256, null=True, verbose_name='reason added')),
                ('steward_inclusion_opt_in', models.BooleanField(default=False, help_text='Did the steward opt in to being included on our map?', verbose_name='steward inclusion opt-in')),
                ('polygon_area', models.DecimalField(blank=True, decimal_places=2, help_text='The area of the polygon in square feet', max_digits=15, null=True, verbose_name='polygon area')),
                ('polygon_width', models.DecimalField(blank=True, decimal_places=2, help_text='The width of the polygon in feet', max_digits=10, null=True, verbose_name='polygon width')),
            ],
            options={
                'permissions': (('view_preview', 'Can view preview map'),),
            },
        ),
        migrations.CreateModel(
            name='LotGroup',
            fields=[
                ('lot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lots.Lot')),
            ],
            options={
                'abstract': False,
            },
            bases=('lots.lot', models.Model),
        ),
        migrations.AddField(
            model_name='lot',
            name='known_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livinglots_lots.Use'),
        ),
        migrations.AddField(
            model_name='lot',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The owner of this lot.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.Owner', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='lot',
            name='owner_contact',
            field=models.ForeignKey(blank=True, help_text='The contact for the owner of this lot.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.OwnerContact', verbose_name='owner contact'),
        ),
        migrations.AddField(
            model_name='lot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lots.LotGroup', verbose_name='group'),
        ),
    ]
