# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_auto_20141024_0058'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='lotgroup',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='lot',
            name='accessible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='archive_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='bbl',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='borough',
            field=models.CharField(choices=[(b'Bronx', b'Bronx'), (b'Brooklyn', b'Brooklyn'), (b'Manhattan', b'Manhattan'), (b'Queens', b'Queens'), (b'Staten Island', b'Staten Island')], default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lot',
            name='gutterspace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='lot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='owner_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcels.Parcel'),
        ),
        migrations.AddField(
            model_name='lotlayer',
            name='lots',
            field=models.ManyToManyField(to='lots.Lot'),
        ),
    ]
