# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_lot_commons_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
