# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_auto_20160627_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='archive_path',
        ),
    ]
