# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 22:52
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0008_lot_development_pending_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='development_pending_explanation',
            field=tinymce.models.HTMLField(blank=True, help_text='If development is pending, let visitors to the site know why.', null=True),
        ),
    ]
