# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-13 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_auto_20160812_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Development pending'),
        ),
    ]
