# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-02-28 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0016_lot_is_waterfront'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='demolition_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='demolition_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='new_public_housing_built',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='new_public_housing_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='nycha_modernization_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='nycha_modernization_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='preservation_trust_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='preservation_trust_voting_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='private_infill_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='radpact_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='radpact_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='section_8_pre_2014',
            field=models.BooleanField(default=False),
        ),
    ]
