# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-02-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0017_auto_20240227_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='building_land_coverage',
            field=models.FloatField(null=True, verbose_name=b'Bldg/Land Coverage - % Density (Population/Acre)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='buildings_nonresidential',
            field=models.PositiveIntegerField(null=True, verbose_name=b'# of Non-Residential Buildings'),
        ),
        migrations.AddField(
            model_name='lot',
            name='buildings_residential',
            field=models.PositiveIntegerField(null=True, verbose_name=b'# of Residential Buildings'),
        ),
        migrations.AddField(
            model_name='lot',
            name='buildings_stories',
            field=models.PositiveIntegerField(null=True, verbose_name=b'# of Stories'),
        ),
        migrations.AddField(
            model_name='lot',
            name='cost_per_room',
            field=models.FloatField(null=True, verbose_name=b'Cost Per Rental Room (As Built)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='cost_total',
            field=models.FloatField(null=True, verbose_name=b'Development Cost'),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_units',
            field=models.PositiveIntegerField(null=True, verbose_name=b'Number of current units'),
        ),
        migrations.AddField(
            model_name='lot',
            name='electricity_residents',
            field=models.BooleanField(default=False, verbose_name=b'Electricity Paid By Residents'),
        ),
        migrations.AddField(
            model_name='lot',
            name='families_fixed_income',
            field=models.PositiveIntegerField(null=True, verbose_name=b'# of Families On Fixed Income'),
        ),
        migrations.AddField(
            model_name='lot',
            name='families_fixed_income_percent',
            field=models.FloatField(null=True, verbose_name=b'% of Families On Fixed Income'),
        ),
        migrations.AddField(
            model_name='lot',
            name='population_public_housing',
            field=models.PositiveIntegerField(null=True, verbose_name=b'Population (Public Housing)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='population_section_8',
            field=models.PositiveIntegerField(null=True, verbose_name=b'Population (Section 8)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='population_total',
            field=models.PositiveIntegerField(null=True, verbose_name=b'Population (Total)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='private_management',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='rent_avg',
            field=models.FloatField(null=True, verbose_name=b'Avg. Monthly Gross Rent'),
        ),
        migrations.AddField(
            model_name='lot',
            name='rental_rooms',
            field=models.PositiveIntegerField(null=True, verbose_name=b'Number of rental rooms'),
        ),
        migrations.AddField(
            model_name='lot',
            name='senior_development',
            field=models.BooleanField(default=False, verbose_name=b'Senior Development'),
        ),
        migrations.AddField(
            model_name='lot',
            name='total_area',
            field=models.FloatField(null=True, verbose_name=b'Total Area - Sq. Ft.'),
        ),
        migrations.AddField(
            model_name='lot',
            name='total_units',
            field=models.PositiveIntegerField(null=True, verbose_name=b'Number of total units'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='new_public_housing_built',
            field=models.BooleanField(default=False, verbose_name=b'New Public Housing Built'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='new_public_housing_planned',
            field=models.BooleanField(default=False, verbose_name=b'New Public Housing Planned'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='nycha_modernization_complete',
            field=models.BooleanField(default=False, verbose_name=b'NYCHA Completed Modernization'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='nycha_modernization_planned',
            field=models.BooleanField(default=False, verbose_name=b'NYCHA-managed Modernization Planned'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='preservation_trust_complete',
            field=models.BooleanField(default=False, verbose_name=b'Preservation Trust Conversion Complete'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='preservation_trust_voting_planned',
            field=models.BooleanField(default=False, verbose_name=b'Voting Planned for Preservation Trust Section 8 Conversion'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='private_infill_planned',
            field=models.BooleanField(default=False, verbose_name=b'Private Infill Planned'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='radpact_converted',
            field=models.BooleanField(default=False, verbose_name=b'RAD/PACT - Converted to Section 8 Under Private Management'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='radpact_planned',
            field=models.BooleanField(default=False, verbose_name=b'Planned RAD/PACT - Section 8 Conversion Under Private Management'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='section_8_pre_2014',
            field=models.BooleanField(default=False, verbose_name=b'Conversions to Section 8 Completed Prior to 2014'),
        ),
    ]
