# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-02-28 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0018_auto_20240227_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='building_land_coverage',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Bldg/Land Coverage - % Density (Population/Acre)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='buildings_nonresidential',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'# of Non-Residential Buildings'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='buildings_residential',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'# of Residential Buildings'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='buildings_stories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'# of Stories'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='cost_per_room',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Cost Per Rental Room (As Built)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='cost_total',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Development Cost'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='current_units',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Number of current units'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='families_fixed_income',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'# of Families On Fixed Income'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='families_fixed_income_percent',
            field=models.FloatField(blank=True, null=True, verbose_name=b'% of Families On Fixed Income'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='population_public_housing',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Population (Public Housing)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='population_section_8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Population (Section 8)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='population_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Population (Total)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='private_management',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='rent_avg',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Avg. Monthly Gross Rent'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='rental_rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Number of rental rooms'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='total_area',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Total Area - Sq. Ft.'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='total_units',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Number of total units'),
        ),
    ]
