# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-02-28 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0019_auto_20240227_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='radpact_conversion_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'RAD/PACT Conversion Date / Anticipated Conversion Date'),
        ),
        migrations.AddField(
            model_name='lot',
            name='radpact_developers',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'RAD/PACT Developers'),
        ),
        migrations.AddField(
            model_name='lot',
            name='radpact_general_contractor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'RAD/PACT General Contractor'),
        ),
        migrations.AddField(
            model_name='lot',
            name='radpact_property_manager',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'RAD/PACT Property Manager'),
        ),
        migrations.AddField(
            model_name='lot',
            name='radpact_social_service_provider',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'RAD/PACT Social Service Provider'),
        ),
        migrations.AddField(
            model_name='lot',
            name='radpact_status',
            field=models.CharField(blank=True, choices=[(b'Construction Complete', b'Construction Complete'), (b'Under Construction', b'Under Construction'), (b'Planning & Engagement', b'Planning & Engagement')], max_length=50, null=True, verbose_name=b'RAD/PACT Status'),
        ),
    ]
