# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-02-29 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0021_auto_20240228_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='radpact_status',
            field=models.CharField(blank=True, choices=[(b'Construction Complete', b'Construction Complete'), (b'Under Construction', b'Under Construction'), (b'Planning & Engagement', b'Planning & Engagement'), (b'Developments Under Consideration by HUD for Future Section 8 Conversions', b'Developments Under Consideration by HUD for Future Section 8 Conversions')], max_length=50, null=True, verbose_name=b'RAD/PACT Status'),
        ),
    ]
