# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-03-06 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0023_auto_20240305_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Density (Population/Acre)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='building_land_coverage',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Bldg/Land Coverage %'),
        ),
    ]
