# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-04-03 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0028_auto_20240401_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='private_management',
        ),
    ]
