# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-04-18 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0029_remove_lot_private_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='shpo_landmark_eligible',
            field=models.BooleanField(default=False, verbose_name=b'SHPO Landmark Eligible'),
        ),
        migrations.AddField(
            model_name='lot',
            name='shpo_landmark_listed',
            field=models.BooleanField(default=False, verbose_name=b'SHPO Landmark Listed'),
        ),
    ]
