# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livinglots_mailings', '0003_mailing_text_flatblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='html_template_name',
            field=models.CharField(blank=True, help_text='The path to the template to use when building the mailing html', max_length=256, null=True, verbose_name='html template name'),
        ),
    ]
