# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 00:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import feincms.module.medialibrary.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallylinkedmediafilecontent',
            name='mediafile',
            field=feincms.module.medialibrary.fields.MediaFileForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialibrary.MediaFile', verbose_name='media file'),
        ),
        migrations.AlterField(
            model_name='mediafilecontent',
            name='mediafile',
            field=feincms.module.medialibrary.fields.MediaFileForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medialibrary.MediaFile', verbose_name='media file'),
        ),
    ]
