# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-13 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20160813_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcontent',
            name='urlconf_path',
            field=models.CharField(choices=[(b'faq.urls', 'FAQ'), (b'extraadmin.cms_urls', 'Extra admin functions'), (b'livinglots_lots.map_urls', 'Lots map'), (b'reviewpathways.urls.urlpatterns', 'Review Pathways'), (b'elephantblog.urls', 'Blog'), (b'contact_form', 'Contact form'), (b'organizingpathways.urls.urlpatterns', 'Organizing Pathways')], max_length=100, verbose_name='application'),
        ),
    ]
