# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerpathways', '0003_ownerpathway_only_landmarked_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpathway',
            name='only_urban_renewal_lots',
            field=models.BooleanField(default=False),
        ),
    ]
