# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('livinglots_lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundtruthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('actual_use', models.TextField(help_text='How is this actually being used?', verbose_name='actual use')),
                ('contact_name', models.CharField(help_text="What's your name?", max_length=50, verbose_name='contact name')),
                ('contact_email', models.EmailField(blank=True, help_text='Who can we email for more information?', max_length=254, null=True, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, help_text='Who can we call for more information?', max_length=20, null=True, verbose_name='contact phone')),
                ('added', models.DateTimeField(auto_now_add=True, help_text=b'When this record was added', verbose_name='date added')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livinglots_lots.Use', verbose_name='use')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
