# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lots', '0002_auto_20160517_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='commons_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='lot',
            name='commons_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
