# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_auto_20160517_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='commons_type',
            field=models.CharField(choices=[(b'library', b'library'), (b'post office', b'post office'), (b'public housing', b'public housing'), (b'vacant lot / garden', b'vacant lot / garden'), (b'waterfront', b'waterfront')], default='vacant lot / garden', max_length=25),
            preserve_default=False,
        ),
    ]
