# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 21:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0007_remove_lot_archive_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='development_pending_explanation',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
