# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0010_auto_20160813_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='remote',
            field=models.BooleanField(default=False, help_text='Is the lot from a remote site?'),
        ),
        migrations.AddField(
            model_name='lot',
            name='remote_locked',
            field=models.BooleanField(default=False, help_text='When refreshing lots from the remote site, can we update this one?'),
        ),
        migrations.AddField(
            model_name='lot',
            name='remote_pk',
            field=models.PositiveIntegerField(blank=True, help_text='What is the id of the lot on the remote site?', null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='remote_site',
            field=models.CharField(blank=True, help_text='Which remote site is the lot from?', max_length=50, null=True),
        ),
    ]
