# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0014_auto_20170516_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='commons_type',
            field=models.CharField(choices=[(b'library', b'library'), (b'park', b'park'), (b'park building', b'park building'), (b'post office', b'post office'), (b'public housing', b'public housing'), (b'vacant lot / garden', b'vacant lot / garden'), (b'waterfront', b'waterfront')], max_length=25),
        ),
    ]
