# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-02-29 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0020_auto_20240227_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='buildings_stories',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=b'# of Stories'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='new_public_housing_built',
            field=models.BooleanField(default=False, verbose_name=b'New Public Housing Built Since 1998'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='new_public_housing_planned',
            field=models.BooleanField(default=False, verbose_name=b'New Public Housing Planned Since 1998'),
        ),
    ]
