# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-03-06 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0022_auto_20240228_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='demolition_completed',
            field=models.BooleanField(default=False, verbose_name=b'Demolition Completed'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='demolition_proposed',
            field=models.BooleanField(default=False, verbose_name=b'Demolition Proposed'),
        ),
    ]
