# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-03-06 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0025_auto_20240305_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='electricity_residents',
            field=models.BooleanField(default=False, verbose_name=b'Electricity Paid By Residents'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='senior_development',
            field=models.CharField(blank=True, choices=[(b'PARTIALLY', b'partially'), (b'EXCLUSIVELY', b'exclusively')], max_length=50, null=True, verbose_name=b'Senior Development'),
        ),
    ]
