# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-04-02 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0027_lot_private_infill_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='section_8_pre_2014',
            field=models.BooleanField(default=False, verbose_name=b'Section 8 Completed Prior to 2014'),
        ),
    ]
